Added the origin and behaviour for the public route in cloudfront
NMDSdevopsServiceAdm/Infra pull request #42
Opened 2024-01-05 15:11 UTC by Zuhal-Ayob

# Work done 

- Added the origin and behaviour for public s3

2024-01-08 12:25 UTC, magicmilo approved these changes

2024-01-08 12:25 UTC, magicmilo commented on terraform/modules/frontend/cloudfront.tf
> +    ssl_support_method  = "sni-only"
Two spaces here before the = might want it to be one

2024-01-08 14:02 UTC, sbt92 requested changes
This requires further work

2024-01-09 14:39 UTC, magicmilo approved these changes

2024-01-09 15:12 UTC, sbt92 approved these changes
LGTM

2024-01-09 15:13 UTC, merged